### ISSUE TITLE
MISTIC-SL dataset

### ISSUE THREAD

**Issue by Finspire13** [rdipietro/miccai-2016-surgical-activity-rec#1]
Dear @rdipietro 

Has any progress been made to release the MISTIC-SL dataset? 
It will be of great help for research if MISTIC-SL is publicly available. 

Thank you

**Comment by rdipietro** [comment]
Hi,

I'm sorry, not that I know of.

I'd recommend emailing Anand Malpani (coauthor) to express interest. His info is available here: https://cirl.lcsr.jhu.edu/people/
